# Generated item: 2024-01-22 22:32:23
code --install-extension aldijav.golangwithdidi
code --install-extension AMiner.codegeex
code --install-extension antfu.iconify
code --install-extension antfu.smart-clicks
code --install-extension antfu.unocss
code --install-extension antfu.where-am-i
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension ckolkman.vscode-postgres
code --install-extension Codeium.codeium
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dyno-nguyen.vscode-dynofileutils
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension GitHub.remotehub
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension jnbt.vscode-rufo
code --install-extension jock.svg
code --install-extension kaiwood.endwise
code --install-extension kamikillerto.vscode-colorize
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension maggie.eslint-rules-zh-plugin
code --install-extension meganrogge.template-string-converter
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.remote-repositories
code --install-extension naumovs.color-highlight
code --install-extension nhoizey.gremlins
code --install-extension nonylene.dark-molokai-theme
code --install-extension pflannery.vscode-versionlens
code --install-extension pranaygp.vscode-css-peek
code --install-extension premparihar.gotestexplorer
code --install-extension qiu8310.minapp-vscode
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension redjue.git-commit-plugin
code --install-extension ritwickdey.LiveServer
code --install-extension sburg.vscode-javascript-booster
code --install-extension Shopify.ruby-lsp
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension syler.sass-indented
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension Vue.volar
code --install-extension w88975.code-translate
code --install-extension xabikos.JavaScriptSnippets
code --install-extension YoavBls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
code --install-extension zxh404.vscode-proto3
